version: "3"
services:
  opensearch-node:
    restart: always
    image: opensearchproject/opensearch:latest
    container_name: ec-opensearch-node
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.seed_hosts=opensearch-node
      - cluster.initial_master_nodes=opensearch-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9205:9200
      - 9605:9600 # required for Performance Analyzer

  opensearch-dashboards:
    restart: always
    image: opensearchproject/opensearch-dashboards:latest
    container_name: ec-opensearch-dashboards
    ports:
      - 5605:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node:9200"]'

  file-storage:
    restart: always
    image: minio/minio:RELEASE.2022-06-11T19-55-32Z
    container_name: ec-file-storage
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Ecommerce-1234
      MINIO_SERVER_URL: "http://localhost:9000"
    command: server --console-address ":9001" /file-storage-volume
    volumes:
      - file-storage-volume:/file-storage-volume
    ports:
      # Files will be served via this port
      - 9002:9000
      # Admin console can be access via this port
      - 9003:9001
volumes:
  opensearch-data:
  file-storage-volume:
networks:
  opensearch-net:
